import { Inter } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/todo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List Next.js",
  description: "Generated by Mohamed Khaled",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodoProvider>{children}</TodoProvider>
      </body>
    </html>
  );
}
